apiVersion: v1
kind: Service
metadata:
  name: login-portal
  namespace: hpe
  labels:
    app: login-portal
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: login-portal
